# Generated by Django 4.0.1 on 2022-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='title',
            new_name='name',
        ),
    ]
