# Generated by Django 4.0.1 on 2022-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_deal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
