# Generated by Django 4.0.1 on 2022-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.CharField(max_length=400),
        ),
    ]
