# Generated by Django 4.0.1 on 2022-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='totalRating',
            field=models.IntegerField(default=0),
        ),
    ]
