# Generated by Django 4.0.1 on 2022-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_deal_totalrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='degree',
            field=models.IntegerField(default=3),
        ),
    ]
